run:
	g++ -o unmodified_peterson_lab_8 iface.cpp
	g++ -o modified_peterson_lab_8 "iface copy.cpp" -lpthread
	g++ -o unmodified_peterson_lab_9 lab9_test.cpp
	g++ -o modified_peterson_lab_9 "lab9_test copy.cpp" -lpthread
	g++ -o lab8_atomic_peterson iface_peterson_atomic.cpp -lpthread
	./unmodified_peterson_lab_8
	./modified_peterson_lab_8
	./unmodified_peterson_lab_9
	./modified_peterson_lab_9
	./lab8_atomic_peterson
build:
	g++ -o unmodified_peterson_lab_8 iface.cpp
	g++ -o modified_peterson_lab_8 "iface copy.cpp" -lpthread
	g++ -o unmodified_peterson_lab_9 lab9_test.cpp
	g++ -o modified_peterson_lab_9 "lab9_test copy.cpp" -lpthread
	g++ -o lab8_atomic_peterson iface_peterson_atomic.cpp -lpthread
